image: node:23-alpine

stages:          # List of stages for jobs, and their order of execution
  - test

test:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - npm i 
    - echo "tout a été installé"
    - npm run test
    - echo "les tests sont passés"
