image: node:18

stages:
  - install
  - test
  - build
 
before_script:
  - apt-get update && apt-get install -y unzip git zip
  
cache:
  key: npm-cache
  paths:
    - node_modules/



install_dependencies:
  stage: install
  script:
    - npm install
 
build_prod:
  stage: build
  dependencies:
    - install_dependencies  # Utilise node_modules sans réinstaller
  script:
    - echo "Création de l'archive pour la branche de production"
    - zip -r my_project_artifact.zip . 
  artifacts:
    paths:
      - my_project_artifact.zip
    expire_in: 1 week  # Archive nettoyée après une semaine
  only:
    - main  # Exécution uniquement sur la branche principale