image: node:18

stages:
  - install
  - test
  - build

cache:
  key: npm-cache
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm i
  artifacts:
    paths:
      - node_modules/


build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
  only:
    - main