 
image: node:18

stages:
  - install
  - build

before_script:
  - apt-get update && apt-get install -y unzip git zip

cache:
  key: npm-cache
  paths:
    - node_modules/

install_dependencies:
  stage: install
  script:
    - npm i



build_prod:
  stage: build
  script:
    - echo "Création de l'archive pour la branche de production"
    - zip -r my_project_artifact.zip .  # Crée l'archive de tout le répertoire
  only:
    - main  # Ce job ne s'exécute que sur la branche 'prod'
  artifacts:
    paths:
      - my_project_artifact.zip  # Spécifie le fichier à garder un artifact
    expire_in: 1 week  # Optionnel : spécifie la durée de vie de l'artifact
